### ISSUE TITLE
LLVM IR not generated (c2c crash) in certain use-case

### ISSUE THREAD

**Issue by xor-gate** [c2lang/c2compiler#19]
Using version `f8fe89b`

**recipe.txt**
```
executable simple
    $warnings no-unused
    $generate-ir
    simple.c2
end
```

**simple.c2**
```
module simple;

public func int32 main(int32 argc, int8*[] argv) {
        char *str = nil;
        return 0;
}
```

**command and output**
```
$ c2c -I
building target simple
NilExpr


Command terminated
```

**Comment by bvdberg** [comment]
Building with asserts enabled will give a 'TODO' assert. I just added the generation of the Nil-ptr,
but the analyser also needs to set the implicit cast from void* to char*. That part is still missing in the analyser, so llvm will give an error when verifying the IR code (IR code should have all implicit casts in place since llvm won't do any casts).

I'll move this up my list, thx!

**Comment by xor-gate** [comment]
Yeah, I was a bit lost because the C-code was correct generated and compiled.

**Comment by bvdberg** [comment]
Yes, there are 2 backends, c and ir. C is almost complete, but ir is in
'Hello world' phase. For the language itself, the backend is not so
important, so i plan to implementate the ir backend, once the language is
nearly done..

Op 9 nov. 2016 2:26 p.m. schreef "Jerry Jacobs" <notifications@github.com>:

>

> Yeah, I was a bit lost because the C-code was correct generated and
compiled.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/c2lang/c2compiler/issues/19#issuecomment-259413862>, or
mute the thread

**Comment by xor-gate** [comment]
I understand, only the  LLVM IR backends need to be able to produce usable assembly/executables. For embedded targets (e.g armv7-m, cortex-m3) this can be painful when migrating from a GCC-ARM based toolchain (or others, e.g Keil armcc) and may even not generate optimized output.

**Comment by luciusmagn** [comment]
> I understand, only the LLVM IR backends need to be able to produce usable assembly/executables. 

IIRC the plan is to make both back-ends able to to produce usable binaries. Producing IR code seems, at least to me, much more complicated than producing C, because of the differences like the one @bvdberg mentioned. IR requires analyser to be complete to cope with all the differences. Since C2 is based on C, there is less differences and generating C code is considerably easier. That is what I think could be the reason IR back-end is only the third main goal after language design completion and C generation.

**Comment by xor-gate** [comment]
Yes that is correct. I saw the video talk at FOSDEM 2015 about this.

**Comment by bvdberg** [comment]
Also, with the CurrentListener change Speed of llvm/clang, keeping the used
interface Small is a big plus. Just keeping IR generation working for Hello
world from llvm 3.3 to 3.9 took some effort...

Op 9 nov. 2016 3:59 p.m. schreef "Jerry Jacobs" <notifications@github.com>:

**Comment by bvdberg** [comment]
Hmm spellchecker: CurrentListener should be 'current'
