### ISSUE TITLE
Suggestion: Rename char to byte

### ISSUE THREAD

**Issue by jgowdy** [c2lang/c2compiler#27]
One of the flawed type names you’ve skipped renaming is char.  Char implies that it contains a character, but in this era of multibyte character encoding formats the name doesn’t really describe something that can hold a character.  Languages like C# have renamed C’s char to byte, and supplied a new char that is capable of containing a 16bit Unicode codepoint.

I believe that any successor to C needs to correct the byte / char / mbcs issue.  Preferably in a manner that eliminates ambiguity for byte and leans towards UTF-8 support.

Love the project, great work so far.

**Comment by luciusmagn** [comment]
Well, the way it is now, char is just an alias for i8, made only for
convenience. It could be more specified that char contains an ASCII
character, rather than any character, though.

I better leave the actual design reponse to bvdberg, though. Remember that
C2 is meant to be only just a bit more high-level than C, so I am not sure
if UTF conversions like in Rust aren't too 'high-level'

regards,

2017-10-08 17:01 GMT+02:00 Jeremiah Gowdy <notifications@github.com>:

**Comment by bvdberg** [comment]
Indeed like Luciasmagn already wrote, C2 is meant for low(er)-level work, where unicode simply is not relevant. There has been a discussion on the forum whether char should be signed or unsigned.
