### ISSUE TITLE
compare and contrast

### ISSUE THREAD

**Issue by dobkeratops** [c2lang/c2compiler#29]
hi, this reminds me of my pet language project (long since ditched, but it demonstrates the kind of features I want)
could you comment on what features you overlap with or could absorb?  https://github.com/dobkeratops/compiler

I dont mind what syntax is used; I just copied rusts syntax as closely as possible to reuse it's existing syntax highlighters

**Comment by lyrachord** [comment]
I wonder you guys why not reconsider syntax is important?

All of exist program languages syntax sucks.

Years ago, AI is very low, it bloom because of CPU speed now.
But compilers slow down, why?

Most syntax let user do compiler things. seems it's  joke.
Syntax sucks. 

Context sensitive syntax is not so hard!
Just a direction.

**Comment by luciusmagn** [comment]
@lyrachord
Context sensitive syntax is not hard, but can also lead to very misleading
programs. Imagine a world where you can have a cool loop like this and this
is nowhere near the actual posibilites:

    for (if for = 0; for < while; (for++, type++)) { }

Compilers don't really slow down and compiler speed doesn't matter. Only
Golang thinks that. Compilers used to be very slow back in the day, I
remember one of the oldest versions of C# compiler being able to freeze my
PC for quite a while even on medium-sized projects. Compilers today instead
of focusing on speed of compilation focus on speed of execution. There is
many more optimizations being done than 20 years ago.

Hardly any syntax lets user do compiler things, which in my mind at least
boils down to 'lexing, parsing, analysing, transforming and producing
output'.

AI used to be slow, but isn't that much anymore because speed is a major
criterion and it scales with computer performance somewhat linearly. Also
keep in mind that nowadays, we use GPU for many AI computations, so CPU
speed isn't the only cause why it is faster today.

Nevertheless, C2C is still a very fast compiler, I imagine the underlying C
compiler might take the most CPU time! The only one who can really provide
statistics is @bvdberg, though.

I hope I cleared some things up :)

Lukáš

2018-02-09 10:56 GMT+01:00 lyrachord <notifications@github.com>:

**Comment by lyrachord** [comment]
@luciusmagn
Well a long story, great!

At first, we need come to an agreement that hard means to perfect even best. And
Seems we are opposition faction, so I will not try to persuade you, of course, you do not as well.
It will be great if there are some points in conversations to let us deep into thought.

Based on above statement, I will not organize my words, just scattered points

Too many things needed to clear, let's pick up one point of Css now, slow down others:)

A single case of for statement with keyword variables proves nothing. Indeed each single point can be done well now. But as to a complete Css language, there is no great sample.

You know, there is a **giant** example that shows Css is hard, JSON parser. It should be the first class.
The true question behind is what? People hope make a best JSON parser.
There are too many styles of trying to do it, and JSON format is relative simple, Why?
People not satisfied with those solutions.

Recent big step of JSON parser should be spring boon's predecessor, there is a big argument at InfoQ years ago. Indeed, the key idea takes example by sf.net vtd-xml project.

I will not say, Statement machine in Old fashion is not not good. MyO is its usecases is not good.
Lexing too early, some semantics responsibility moved to lexing.
** Lexing do too many comparisons, and most of which should be deferred. **

DMD compiles a small regex program with eating 2-3G memory, phew

Syntax does matter
i.e.
Swift no inner class (at least last year) , so there is a kinky parent-child association relationship.
C++11 above let use do lamda captures,  compare to Java capture?

Look Rust ref-bor, seems to be smart, the truth is very stupy.
Indeed many Java developers use array to do C-family pointer operations
So the case of rust ref-bor is just like non-china-culture-zone lack of ablitity to associate

Now some compiler developers do know to remove int long..,
and start using i/16/32... pity, they do not know i1/2/4/8
Many people bad at math?

The key of a language is not for self but for others.

See ya

consider the following code
```java
@Name(name1: value; name2= value;
name3: v1, v2, v3
name4: @Nest(...)(...)(...))
[T, V: Map[T, Iterable & Comparable]] 
Collection[T] f1(V map, array[T] source, int arg1, array[string] masks, int guard){
...
}

test(){
 f1(map{1: a, b, c; 2: d, e, f}, 1, 2, 3, 4, a, b, c, d, e, 4);
 f1(map{1: a, b, c; 2: d, e, f}; 1, 2, 3; 4; a, b, c, d, e; 4);
 f1(map{1: a, b, c; 2: d, e, f}; source: 1, 2, 3; arg1=4; a, b, c, d, e; 4);
//TODO: maybe T is array
///compare the following
"$simple ${complex.expression} other string "
simple~" "~complex.expression
simple~ ~complex.expression~other string ~
simple " " complex.expression " other string "
//with(person) {    println("First name: $firstName, last name: $lastName")}
person :: print("First name is " firstName ", last name is " lastname ",")
person, map :: print("First name is " firstName ", last name is " lastname ", and map to " get(firstName) )

}


```

**Comment by luciusmagn** [comment]
Ah, thank you for your thorough response.

I am not sure that hard means best or perfect, but that perhaps may be me misinterpreting what you meant. In languages, there should be a balance imo.

Yes, the example doesn't prove that much indeed, but it is meant as a little hint what could be. Even with context insensitive keywords, C code can get very confusing, see any entry in the IOCCC contest.

I agree that CSS parsing can have some similarities to parsing JSON, definitely. Neither of them is a programming language though, so learnings gathered there only apply to a certain degree. JSON is pretty easy to parse indeed. That is the main reason I believe that there are many JSON parsers.
Everyone can make a JSON parser as a toy project or to try a new parsing technique, or to compare it to an implementation in another language (HTTP header parsers are used for this too).
I don't think people are dissatisfied with the current solutions, I believe they make their own because they can and because it is neither time consuming nor difficult to figure out.

It is great that Java has a fast parser like Boon, maybe it offsets a bit what a wretched language in terms of design Java is with its lack and refusal of some constructs and unwieldy syntax.

I am a Rust affectionado and a strong supporter of its syntax. Borrowing, ownership, lifetimes and the way it handles references provide a very fast, secure and garbage collector free existence. What exactly do you mean by 'ref-bor'? We don't use this term in the community.
I am not sure about your sentence about Java devs using arrays to do C pointer operations. Either Java has a pointer interface that sucks, or you believe pointers sucks. Without pointers, modern computers aren't a thing. Heck, even old computers wouldn't work. Pointers are essential for low-level programming, regardless of whether you like it or not.

Yes, **short**, **long**, **double** and perhaps other unexplanatory type names are not great. However, in a science that cares very much about bits, i8/i16/i32 make more sense than cramming it under bytes. It is also to provide a familiar feel to newcomers and parity with Rust.

Yes, indeed, programming languages are often intended for a wider audience than the creator. I completely agree with that point. 

I have considered your code example. It seems like something that would be annoying to parse and quite unwieldy. This is something that would allow for a great deal of variability resulting in inconsistency and unreadability.
The syntax may be usable for some high-level functional language hybrid, but for low-level like C2, not so much.

See our philosophy and design goals for what C2 is all about: http://c2lang.org/site/

Cheers,
Lukáš

**Comment by luciusmagn** [comment]
@dobkeratops 
I like your pet project very much. I am not sure what features would @bvdberg like to adopt, but I'd definitely like seeing more Rustisms in C2. Stack-based closures and some form of operator overloading would definitely be one thing that I'd love to see in C2.

**Comment by lyrachord** [comment]
Yes JSON parsing is easy. 

Though easy, in most cases the easier the harder to come to the more perfect.
I insist on the unsatisfication with talking points: 

- many people try to improve JSON syntax to widen its limit
- some people try to out-of-order way to speed parsing at c-level, I guess JIT way will be, like regex's JIT

With respect to Java pointer:  
When programming NIO applications, some developer maybe need directly memory management in the face of flood of user connections. These NIO memory management work almost same as native pointer operation. Essentially we can regard them without distinction except the difference between pure pointer and offset. 
Same cases when FFI-like-ing with native buffer and function invocation.

Yes over these years java langue does be still as dead without truely advance, maybe its simon-pure contribution only mitigation of pointer-error-prone and JIT.
At langue upper level, the important lesson from java is how to use pointer.
Happy to see ya a rust dead-iron-fan:) 
And yes you do know what ref-bor means:)  reference and borrowing
BTW there is an ORM project hibernate, an implementation of a 98's paper.
Hibernate has a good application of one important philosophy: DBE declaration by exception.
Now there is a work to do: count rust ref-bor usecases. And I bet :) Im loser if bor>ref. In return, rust will die at bor<ref
Here I clear: I do not blame the backend concept of ref-bor. We just talk about the face, syntax.
As to implementation, another story.
As you know, there is no bit data type at all at cpu level (of course there do at core level).
There are only bit operations. So bits not proper. That's the first point.
And In the wake of AI and programming growing, non-developer start to do programming. So math cares. Byte is easier to count for these people? So We should use bytes-1/2/4/8/16-form instead of bits. There is no exception even scientist, they do programming rather than counting.

The aforementioned code's key is the fact that there are tooo many programming langues.
The many produces tooo many preferences. 
Based on this point, now we have 2 choices: 
1, Add compiler switches to let user use their preferred syntax.
2, Accept different syntaxes in a local permission scope
Those code shows our endeavor.

Actually we are almost always processing string, except data science, so it is certainly worth impoving string usage and syntax.
BTW which one is in your dish?

**Comment by lyrachord** [comment]
@dobkeratops
BTW I'm sorry for occupation of your topic

**Comment by dobkeratops** [comment]
r.e. context sensitive syntax .. certainly in rust it is initially frustrating that you sometimes write ```Foo::<T>``` but i think this is the lesser evil given how much easier the language is to parse. context-free syntax gives more chance to change the syntax later, or make tools that present the same programs in a more readable way.

In the evolution of rust, they considered using square brackets for type-parameters (like scala?) .. I actually think that's superior in retrospect, however we are where we are with many languages having copied C++. i guess you can make ```<ident>``` always parse as a type-parameter, but once you start wanting expressions as type-parameters i think it gets messier.

In retrospect I think I would ideally choose a uniform syntax between types and expressions/statements,  I think this would facilitate 'dependant types'? .. e.g. expressions that manipulate types would effectively use 'operator overloads' that worked at the type level at compile-time? (* disclaimer, i'm not an expert on 'dependant types', i've just heard of them in Idris etc.. i sort of got the impression thats how they worked?)

When I was writing my pet-language, I just wanted to mirror Rusts' syntax as closely as possible to increase the chance anyone else could read my source (i.e. there's a higher chance they'd understand Rust rather than anything I invented)

**Comment by bvdberg** [comment]
1. Multiple return value could be implemented in a C-like language for that matter. I saw that for Go 2 they changed that part again since the resulting code with res,err = myfunc() was causing a lot of duplicate code. I think it brings that big an improvement, while causing more complexity. Alternatively,
some languages (Ada) allow the **in/out/inout** keyword for arguments to specify out-parameters.

2. I don't like type inference, it only cause obscurity at the 'benefit' of not having to type a few characters.

3. Polymorphic function require symbol mangling to work and that is definitely something to avoid

4. I'm not familiar with 'Rust style enums'? In C2, all enum constants are in the enum's namespace. What could be (easily) done is to add _enum functions_, just like struct functions.

5. I agree with @lerno 

6. The idea on C2 is to be an _evolution_ of C. Changing this would make it something completely different

7. yes out of the picture

8. I love closures, but they are a complete non-fit. They only work when functions are first class citizens, so basically only in functional/higher languages

9. same

10. I think it adds complexity. I've never used them after all these years of C programming

**Comment by lerno** [comment]
@bvdberg Rust enums are really tagged unions (**NOT** enums! the name is extremely confusing, think of it as a variant of of object orientation, with the "enum" being a group of related classes), they make it possible to work in a semi object oriented-ish programming style. I think it's possible that a special syntax for a tagged union could be interesting eventually, but the Rust style enum has a very special syntax that's supposed to match Rust's pattern matching that would be very out of place.

**Comment by lerno** [comment]
@bvdberg statement expressions are very useful when building certain types of macros.
