### ISSUE TITLE
Decide, document and implement identifier max lengths

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#49]
Right now, names for identifiers etc are (as far as I can tell) arbitrarily long. That might be fine right now, but it can create problems further down the line, when trying to allocate things statically. Besides, I would also say that arbitrarily long identifiers aren't a good idea anyway.

C99 has a 31 characters (internal 63), Java has 65535(!).

The advantage of a lower limit is hashing and memory usage. Any power of two up to 255 feels reasonable. Maybe 63 or 127?

    ARatherLongNameForThisStructIs31 foo;
    IfWeGoFor63CharactersThenAStructCanBeJustAsLongAsThisOneHere12 bar;

This max length is excluding the module namespace though!

**Comment by luciusmagn** [comment]
I'd argue that even 31 might be enough. Requiring too long identifiers either indicates some memery or horrible program design. I can't think of a single case where I needed more than 15-ish characters, but ymmv.

**Comment by lerno** [comment]
63 gives you more margin though.

**Comment by bvdberg** [comment]
31 should be enough for everyone (Where did I hear that before?). For most symbols, the only 'mangling' is indeed the module_symbol, allowing for 31 for both the module and the symbol would result in a total upper bound 63, so that's nice. 

There are 2 other situations I can think of:
1. Struct functions: _module_type_func_
2. Enum constants: _module_type_constant_

When i'm programming C2, I still haven't settled on the style of names for modules. Since they should be globally unique, short names like _net_ are not so good.  I currently use longer names like _http_networking_ and then import them with 'import http_networking as net'

A total upper bound would very handy for symbol manipulation later on (when c2c generates IR directly and does object symbol handling). I think just checking+forcing the 'type_func' or 'type_constant' part to be 31 in total is the best solution.

**Comment by bvdberg** [comment]
One other thing that came to mind is this. Currently if you have a function _my_function()_ in module _foo_, the resulting symbol is _foo_my_function_. From this symbol, it's impossible to get the original module and function name. It might be module _foo_my_ and function _function_ or _foo_ and _my_function_. A human could guess, but tools not so much

**Comment by lerno** [comment]
Another is to have the artificial $ as separator that's rejected by the compiler but acceptable internally. So foo$my_function. This is the scheme that java uses I think.

**Comment by bvdberg** [comment]
I once tried to search a specification for valid object names for the linker, but couldn't find anything then. The ELF specification was also vague i remember. So I wasn't sure what to use. For now underscore seems ok, especially for generation C as well..

**Comment by bvdberg** [comment]
implemented
