### ISSUE TITLE
Missing debugging code in IR generation for LLVM

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#52]
Clang emits various debugging pointers which helps debugging the code. Since the code generation is already based on Clang, we should probably add this to C2's code generation as well.

Following Clang closer in the code gen will also help in quickly getting solid IR out. (Unless we get som contributor who is an LLVM expert)

**Comment by bvdberg** [comment]
Yes. I have looked at IR code itself, but very little at how Clang actually emits that. The reason is that for the language the back-end (C/IR-generation) is actually the least interesting. I wanted to focus on the actual language design first. And the C back-end was a lot easier to write and also allowing testing.

Another reason was that the interfaces tended to change with LLVM versions, so even keeping the 'hello world' example running took effort. I think those interfaces have stabilized, since I haven't had any issues porting to a new LLVM lately.

**Comment by bvdberg** [comment]
LLVM is still far of currently..closing this for now.
